title: Adverts-Mediation
show_downloads: false
google_analytics:

repository: distriqt/ANE-Adverts-Mediation
exclude: ["_Sidebar.md, _Footer.md"]
theme: jekyll-theme-minimal

gems: 
  - jekyll-redirect-from

